name: evervent_server
description: The backend from evervent.
version: 0.0.1
author: CodeDoctorDE, redsolver

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0+1
  crypto_keys: ^0.1.3
  shared:
    path: ../shared
  

dev_dependencies:
  test: ^1.15.3
  aqueduct_test: ^1.0.1
dependency_overrides:
  analyzer: ^0.40.0
