name: shared
description: Shared Dart Code between app and server.
author: CodeDoctorDE, redsolver
dependencies:
  hive: ^1.4.1+1
dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
environment:
  sdk: ">=2.5.0 <3.0.0"